### PR TITLE
improve zplug integration

### PR DESCRIPTION
**Pull request by ninrod**
this improves zplug integration. right now, with zplugv2, we can't use the plugin as is.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Isn't there another way to do that? I am obviously breaking the setup for every other user.

**Comment by ninrod** [comment]
hi @vincentbernat. You're right. I think now I've managed to maintain backwards compatibility. What you think?

**Comment by vincentbernat** [comment]
That's OK. Do you want to squash your commits or should I do it myself (it's two clicks for me)?

**Comment by ninrod** [comment]
Hi, thanks. It is pretty fast from my end too. Already squashed it. I think it is ready now.

**Pull request merged**
